### PR TITLE
Missing assets

### PR DESCRIPTION
**Pull request by persn**
Fix for Issue #3. Detailed description of accomplished work in the commit messages

### CODE REVIEW

**Comment by Wano-k** [comment]
Thank you! Well I'm kind of annoyed by using XNA format. First because I have to think about the fact that it's a game template that should be edited only by setting its datas files (.JSON or images here). How a user could change, for example, his floor textures if it needs to be a .xnb file?

**Comment by persn** [comment]
That depends a tons on how you're envisioning this software is going to work. Most game makers in my experience has a build step to it, where data is converted before the game is run. So:
1. Paper Maker organizes raw data and code into projects with an editor
2. If the user presses an option like "Build" or "Build and Run"
   2a. Raw images, audio and other stuff is converted by the MonoGame pipeline tool
   2b. Paper Maker converts the remaining files into a game project the end-user can play and distribute

If we look at it from the end-users perspective, they might not be very happy by the prospect of having all their assets open and view-able by anyone in the end product.

**Comment by Wano-k** [comment]
Yeah I agree. So it would only be used for the end of a project when the user wants to share his work (such as in RPG Maker). But when an user is building a project, its ressources should not be converted. I'm currently working on that part, so should we let this stuff like that? Plus, how can we convert all the content without doing it manually?

**Comment by persn** [comment]
That's a broad and difficult issue, I haven't invested enough thought into this to tackle it fully on. But the fact remains that the repo in its current implementation isn't very plug n' play unless the assets goes over to the compile folder automatically.

I could simply change my pull request so that it copies the image files over instead of converting them, the MonoGame Pipeline tool supports that. Would that be a satisfactory solution for now?

**Comment by Wano-k** [comment]
Yeah let's do that for now. Be sure that the `Content` folder into `Game` folder is always the same than the other `Content` folder when compiling!

**Comment by persn** [comment]
Updated. I changed it to copy the images instead of converting to the .xnb format. in the pipeline tool. And I dropped the commit that altered the code to read from .xnb instead of a filestream.

**Pull request merged**
